<a href="https://colab.research.google.com/github/RuthMaya/Evaluaci-n/blob/main/ESP_ACTIVIDAD_5_(Evaluaci%C3%B3n)_PARTE_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ACTIVIDAD 5 (Evaluación) PARTE 2**
## **Ruth Maya López**
## **A01707467**

In [33]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## **ESP**

In [34]:
esp = pd.read_csv("Datos_limpios_ESP.csv", encoding= 'unicode_escape')

<ipython-input-34-13843ddbd061>:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) have mixed types. Specify dtype option on import or set low_memory=False.
  esp = pd.read_csv("Datos_limpios_ESP.csv", encoding= 'unicode_escape')

In [35]:
esp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19656 entries, 0 to 19655
Data columns (total 73 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Unnamed: 0                                    19656 non-null  object
 1   id                                            19656 non-null  object
 2   scrape_id                                     19656 non-null  object
 3   host_id                                       19656 non-null  object
 4   host_listings_count                           19656 non-null  object
 5   host_total_listings_count                     19656 non-null  object
 6   latitude                                      19656 non-null  object
 7   longitude                                     19656 non-null  object
 8   accommodates                                  19656 non-null  object
 9   bedrooms                                      19656 non-null  object
 10  beds                                          19656 non-null  object
 11  minimum_nights                                19656 non-null  object
 12  maximum_nights                                19656 non-null  object
 13  minimum_minimum_nights                        19656 non-null  object
 14  maximum_minimum_nights                        19656 non-null  object
 15  minimum_maximum_nights                        19656 non-null  object
 16  maximum_maximum_nights                        19656 non-null  object
 17  minimum_nights_avg_ntm                        19656 non-null  object
 18  maximum_nights_avg_ntm                        19656 non-null  object
 19  availability_30                               19656 non-null  object
 20  availability_60                               19656 non-null  object
 21  availability_90                               19656 non-null  object
 22  availability_365                              19656 non-null  object
 23  number_of_reviews                             19656 non-null  object
 24  number_of_reviews_ltm                         19655 non-null  float64
 25  number_of_reviews_l30d                        19655 non-null  float64
 26  review_scores_rating                          19655 non-null  float64
 27  review_scores_accuracy                        19655 non-null  float64
 28  review_scores_cleanliness                     19655 non-null  float64
 29  review_scores_checkin                         19655 non-null  float64
 30  review_scores_communication                   19655 non-null  float64
 31  review_scores_location                        19655 non-null  float64
 32  review_scores_value                           19655 non-null  float64
 33  calculated_host_listings_count                19655 non-null  float64
 34  calculated_host_listings_count_entire_homes   19655 non-null  float64
 35  calculated_host_listings_count_private_rooms  19655 non-null  float64
 36  calculated_host_listings_count_shared_rooms   19655 non-null  float64
 37  reviews_per_month                             19655 non-null  float64
 38  listing_url                                   19655 non-null  object
 39  last_scraped                                  19655 non-null  object
 40  source                                        19655 non-null  object
 41  name                                          19655 non-null  object
 42  description                                   19655 non-null  object
 43  neighborhood_overview                         19655 non-null  object
 44  picture_url                                   19655 non-null  object
 45  host_url                                      19655 non-null  object
 46  host_name                                     19655 non-null  object
 47  host_since                                    19655 non-null  object
 48  host_location                                 19655 non-null  object
 49  host_about                                    19655 non-null  object
 50  host_response_time                            19654 non-null  object
 51  host_response_rate                            19654 non-null  float64
 52  host_acceptance_rate                          19654 non-null  float64
 53  host_is_superhost                             19654 non-null  object
 54  host_thumbnail_url                            19654 non-null  object
 55  host_picture_url                              19654 non-null  object
 56  host_neighbourhood                            19654 non-null  object
 57  host_verifications                            19654 non-null  object
 58  host_has_profile_pic                          19654 non-null  object
 59  host_identity_verified                        19654 non-null  object
 60  neighbourhood                                 19654 non-null  object
 61  neighbourhood_cleansed                        19654 non-null  object
 62  property_type                                 19654 non-null  object
 63  room_type                                     19654 non-null  object
 64  bathrooms_text                                19654 non-null  object
 65  amenities                                     19654 non-null  object
 66  price                                         19654 non-null  float64
 67  has_availability                              19654 non-null  object
 68  calendar_last_scraped                         19654 non-null  object
 69  first_review                                  19654 non-null  object
 70  last_review                                   19654 non-null  object
 71  license                                       19654 non-null  object
 72  instant_bookable                              19654 non-null  object
dtypes: float64(17), object(56)
memory usage: 10.9+ MB

### **a) host_acceptance_rate> 50%**

In [36]:
filtroa=esp[esp['host_acceptance_rate'] > 50]
filtroa

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,14551,2.02303E+13,57237,1,5,41.9965,2.83646,2,1,...,Private room,1 private bath,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",42.0,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
2,2,1212820,2.02303E+13,6620645,2,3,42.11284,3.1667,4,1,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Free parking on premises...",74.0,t,01/04/2023,10/06/2013,30/12/2022,HUTG-049542,f
3,3,751638,2.02303E+13,3680160,6,6,42.36958,2.9803,2,1,...,Private room,1 private bath,"[""Hair dryer"", ""Luggage dropoff allowed"", ""Fre...",45.0,t,31/03/2023,23/08/2013,29/08/2022,PG000794,t
5,5,751997,2.02303E+13,3387407,12,12,41.91798,3.16419,4,1,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Pack ân play/Travel cr...",105.0,t,01/04/2023,03/05/2016,26/02/2023,HUTG-016218,t
6,6,752035,2.02303E+13,3387407,12,12,41.91801,3.17085,4,2,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",110.0,t,31/03/2023,02/07/2013,31/10/2021,HUTG-008974,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19649,19648,858000000000000000.0,20230300000000.0,13308911,51.0,59.0,41.72036,2.92986,4,1.0,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",107.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-027601,t
19650,19649,858000000000000000.0,20230300000000.0,507731324,1.0,1.0,42.24504,3.12588,4,1.0,...,Entire home/apt,1 bath,"[""TV"", ""Kitchen""]",75.0,t,01/04/2023,23/03/2023,26/03/2023,Exempt,t
19651,19650,858000000000000000.0,20230300000000.0,26281633,34.0,44.0,41.957265,3.201288,8,4.0,...,Entire home/apt,5 baths,"[""Pets allowed"", ""Smoking allowed"", ""Essentials""]",209.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-001292,t
19652,19651,858000000000000000.0,20230300000000.0,444428600,3.0,3.0,41.69907,2.84408,4,1.0,...,Entire home/apt,1 bath,"[""Kitchen"", ""Pets allowed"", ""Washer""]",52.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG019727,t
19654,19653,858000000000000000.0,20230300000000.0,389605038,111.0,121.0,41.809375,3.05391,4,2.0,...,Entire home/apt,1 bath,"[""Refrigerator"", ""Microwave"", ""Elevator"", ""Pet...",108.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-065236,t

In [37]:
#Corroborar el filtro
filtroa['host_acceptance_rate'].unique()

array([ 90.,  80.,  91., 100.,  57.,  99.,  65.,  64.,  98.,  67.,  74.,
        92.,  71.,  52.,  97.,  95.,  84.,  94.,  83.,  76.,  77.,  96.,
        78.,  93.,  82.,  59.,  87.,  81.,  85.,  58.,  55.,  86.,  60.,
        62.,  88.,  68.,  75.,  70.,  69.,  89.,  72.,  54.,  63.,  73.,
        56.,  79.,  66.,  61.,  53.,  51.])

In [38]:
filtroa.to_csv("filtroa_ESP.csv")
from google.colab import files 
files.download("filtroa_ESP.csv")

### **b) Sólo los registros con categoría “superhost”**

In [39]:
#Filtro por objeto 
filtrob=esp[esp["host_is_superhost"] == "t"]
filtrob

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,14551,2.02303E+13,57237,1,5,41.9965,2.83646,2,1,...,Private room,1 private bath,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",42.0,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
8,8,45400,2.02303E+13,201228,1,2,41.95577,3.21096,4,1,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""E...",83.0,t,01/04/2023,28/12/2010,04/03/2023,HUTG-015895,t
10,10,753604,2.02303E+13,3964191,7,7,41.7173,2.86409,6,3,...,Entire home/apt,1 bath,"[""Carbon monoxide alarm"", ""Free parking on pre...",195.0,t,01/04/2023,08/09/2013,03/09/2022,LLG-000010,f
21,21,106704,2.02303E+13,553059,5,10,41.83631,2.937,5,4,...,Entire home/apt,4.5 baths,"[""Dedicated workspace"", ""Kitchen"", ""Self check...",231.0,t,01/04/2023,19/07/2011,31/12/2022,PG-002599,f
23,23,766763,2.02303E+13,4043268,2,2,41.96041,3.22659,5,2.2,...,Entire home/apt,3 baths,"[""Carbon monoxide alarm"", ""Free parking on pre...",399.0,t,01/04/2023,04/06/2016,16/10/2022,HUTG-043628,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19598,19597,857000000000000000.0,20230300000000.0,137859766,15.0,25.0,42.29087,3.2764,6,3.0,...,Entire home/apt,3 baths,"[""Air conditioning"", ""Free parking on premises...",341.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-060488,t
19602,19601,856000000000000000.0,20230300000000.0,401533317,5.0,5.0,42.05427,3.20685,6,3.0,...,Entire home/apt,1.5 baths,"[""Refrigerator"", ""Microwave"", ""Safe"", ""Free st...",230.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-059959,f
19618,19617,857000000000000000.0,20230300000000.0,225125698,19.0,19.0,42.291029,3.278916,4,2.0,...,Entire home/apt,1 bath,"[""Dedicated workspace"", ""Kitchen"", ""Air condit...",170.0,t,31/03/2023,23/03/2023,26/03/2023,HUTG-060928,t
19629,19628,858000000000000000.0,20230300000000.0,125660503,10.0,13.0,41.78785,3.02869,6,3.0,...,Entire home/apt,2 baths,"[""Air conditioning"", ""Free parking on premises...",207.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-067564,t
19652,19651,858000000000000000.0,20230300000000.0,444428600,3.0,3.0,41.69907,2.84408,4,1.0,...,Entire home/apt,1 bath,"[""Kitchen"", ""Pets allowed"", ""Washer""]",52.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG019727,t

In [40]:
#Corroborar el filtro
filtrob['host_is_superhost'].unique()

array(['t'], dtype=object)

In [41]:
filtrob.to_csv("filtrob_ESP.csv")
from google.colab import files 
files.download("filtrob_ESP.csv")

### **c) Los registros que no hallan verificado identidad “ not identity_verified”**

In [42]:
#Filtro por objeto 
filtroc=esp[esp["host_identity_verified"] == "f"]
filtroc

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
2,2,1212820,2.02303E+13,6620645,2,3,42.11284,3.1667,4,1,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Free parking on premises...",74.0,t,01/04/2023,10/06/2013,30/12/2022,HUTG-049542,f
7,7,1215790,2.02303E+13,3149645,1,1,41.84984,3.1265,7,3,...,Entire home/apt,2 baths,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""F...",60.0,t,01/04/2023,01/07/2013,18/02/2018,HUTG-017955,f
9,9,1222762,2.02303E+13,6404885,1,1,42.21904,2.90744,5,3,...,Entire home/apt,2 baths,"[""Heating"", ""Kitchen"", ""Air conditioning"", ""Wa...",65.0,t,31/03/2023,19/08/2013,14/09/2022,HUTG-012585,f
30,30,784892,2.02303E+13,4073860,1,5,42.39611,3,6,3,...,Entire home/apt,3 baths,"[""Shared pool"", ""Free parking on premises"", ""R...",100.0,t,31/03/2023,11/09/2015,11/09/2015,PG-000599,f
33,33,1242933,2.02303E+13,6774688,1,2,41.85578,3.13043,4,2,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Oven"", ""Dis...",100.0,t,01/04/2023,02/08/2013,29/07/2019,HUTG-019098,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19554,19553,856000000000000000.0,20230300000000.0,5113430,4.0,11.0,41.81861,3.056453,4,2.0,...,Entire home/apt,1.5 baths,"[""Air conditioning"", ""Stainless steel oven"", ""...",182.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-029538,f
19561,19560,856000000000000000.0,20230300000000.0,167394031,1.0,1.0,41.69185,2.81279,8,4.0,...,Entire home/apt,3 baths,"[""Free parking on premises"", ""Refrigerator"", ""...",134.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG002307,t
19562,19561,856000000000000000.0,20230300000000.0,450603533,30.0,30.0,42.26445,3.1793,5,2.0,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Free parking on premises...",168.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-023155,t
19612,19611,857000000000000000.0,20230300000000.0,503009347,14.0,14.0,41.7945,3.04349,7,3.0,...,Entire home/apt,2 baths,"[""Iron"", ""Ethernet connection"", ""Single level ...",161.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-008448,t
19613,19612,857000000000000000.0,20230300000000.0,503009347,14.0,14.0,41.79446,3.04403,7,3.0,...,Entire home/apt,2 baths,"[""Iron"", ""Dishwasher"", ""Washer"", ""Bathtub"", ""H...",161.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-008448,t

In [43]:
#Corroborar el filtro
filtroc['host_identity_verified'].unique()

array(['f'], dtype=object)

In [44]:
filtroc.to_csv("filtroc_ESP.csv")
from google.colab import files 
files.download("filtroc_ESP.csv")

### **d) Los registro cuyo property_type = “Private room” y “Hotel room”**

In [45]:
esp["property_type"].unique()

array(['Private room in condo', 'Private room in loft', 'Entire condo',
       'Private room in bed and breakfast', 'Entire rental unit',
       'Entire home', 'Entire townhouse', 'Entire villa',
       'Private room in home', 'Farm stay', 'Entire guesthouse',
       'Private room in rental unit', 'Entire cottage', 'Entire loft',
       'Entire cabin', 'Entire guest suite',
       'Private room in guest suite', 'Private room in townhouse',
       'Entire chalet', 'Private room in farm stay', 'Hut', 'Castle',
       'Private room in cottage', 'Private room', 'Private room in villa',
       'Barn', 'Entire vacation home', 'Private room in chalet',
       'Entire bungalow', 'Private room in bungalow', 'Casa particular',
       'Shared room in home', 'Entire serviced apartment',
       'Private room in guesthouse', 'Entire bed and breakfast',
       'Tiny home', 'Private room in serviced apartment',
       'Private room in casa particular', 'Earthen home',
       'Private room in hostel', 'Room in serviced apartment',
       'Treehouse', nan, 'Room in boutique hotel', 'Camper/RV', 'Boat',
       'Private room in cabin', 'Floor', 'Shared room in nature lodge',
       'Room in bed and breakfast', 'Entire place', 'Room in hotel',
       'Shared room in rental unit', 'Room in hostel', 'Yurt',
       'Room in aparthotel', 'Campsite', 'Private room in castle',
       'Private room in tiny home', 'Shared room in villa',
       'Private room in hut', 'Private room in resort',
       'Private room in earthen home', 'Private room in treehouse',
       'Tipi', 'Tent', 'Private room in nature lodge',
       'Private room in barn', 'Shared room in hostel',
       'Private room in boat', 'Private room in vacation home',
       'Holiday park', 'Private room in windmill', 'Private room in tent',
       'Shared room in cottage', 'Private room in camper/rv',
       'Private room in pension', 'Shared room in bed and breakfast'],
      dtype=object)

In [46]:
filtrod=esp[(esp["property_type"] == 'Private room') | (esp["property_type"] == "Hotel room")]
filtrod

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
356,356,3054347,2.02303E+13,15550598,2,2,42.28732,3.27713,2,2.5,...,Private room,1 private bath,"[""Air conditioning"", ""Refrigerator"", ""Shampoo""...",109.0,t,01/04/2023,16/06/2014,05/11/2022,HUTG-002595,f
2485,2484,14613107,2.02303E+13,38817324,1,1,42.15369,2.60122,4,1,...,Private room,1 bath,"[""Hair dryer"", ""Iron"", ""Washer"", ""Free parking...",40.0,t,01/04/2023,02/10/2016,15/10/2017,HUTG-020720,f
3135,3134,17117682,2.02303E+13,104655629,10,10,42.1448,2.56848,2,1,...,Private room,1 private bath,"[""Pool"", ""Pets allowed"", ""Hangers"", ""Heating"",...",73.0,t,31/03/2023,25/02/2017,05/12/2022,ATG-000023,f
7839,7838,32997174,2.02303E+13,248354355,1,3,42.15973,2.91132,2,1,...,Private room,1 bath,"[""Sanex body soap"", ""Microwave"", ""First aid ki...",40.0,t,31/03/2023,16/08/2020,22/08/2022,Exempt,f
16666,16665,658000000000000000.0,20230300000000.0,466301894,1.0,1.0,41.72831,2.919324,2,1.0,...,Private room,1.5 baths,"[""Carbon monoxide alarm"", ""Refrigerator"", ""Lon...",50.0,t,01/04/2023,17/07/2022,22/07/2022,HUTB-123456,t
17058,17057,687000000000000000.0,20230300000000.0,104927492,1.0,5.0,42.18328,2.88674,2,1.0,...,Private room,1 private bath,"[""Free parking on premises"", ""Shared outdoor p...",120.0,t,31/03/2023,04/12/2022,12/03/2023,Exempt,f
19023,19022,841000000000000000.0,20230300000000.0,162348326,2.0,2.0,42.30333,3.0,2,1.0,...,Private room,1 private bath,"[""Clothing storage: walk-in closet"", ""Pack â...",80.0,t,01/04/2023,20/03/2023,20/03/2023,Exempt,t

In [47]:
#Corroborar el filtro
filtrod['property_type'].unique()

array(['Private room'], dtype=object)

In [48]:
filtrod.to_csv("filtrod_ESP.csv")
from google.colab import files 
files.download("filtrod_ESP.csv")

### **e) Los registros que cuenten con bathroom > 1**

In [49]:
esp['bathrooms_text'].unique()

array(['1 private bath', '1.5 shared baths', '1 bath', '2 baths',
       '4 baths', '4.5 baths', '2.5 baths', '3 baths', '6.5 baths',
       '1 shared bath', '1.5 baths', '3.5 baths', '3 shared baths',
       '7.5 baths', '6 baths', '8 baths', '5 baths', '7 baths',
       '8.5 baths', '10 baths', '5.5 baths', '2.5 shared baths',
       '5 shared baths', nan, '11 baths', '9.5 baths', '2 shared baths',
       '0 baths', '0 shared baths', '9 baths', '12 baths', 'Half-bath',
       '3.5 shared baths', '13 baths', '18 baths', '15.5 baths',
       '10.5 baths', '5.5 shared baths', 'Shared half-bath', '15 baths',
       '100 baths', '11.5 baths', '6 shared baths', '14.5 baths',
       '13.5 baths', '14 baths'], dtype=object)

In [50]:
filtroe=esp[~(esp["bathrooms_text"] == '1 bath')  & ~(esp["bathrooms_text"] == "1 private bath")]
filtroe

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
1,1,1205757,2.02303E+13,6586355,1,1,41.79304,2.77412,2,1,...,Private room,1.5 shared baths,"[""Free parking on premises"", ""Refrigerator"", ""...",47.0,t,31/03/2023,01/08/2013,26/06/2022,HUTG-049542,f
7,7,1215790,2.02303E+13,3149645,1,1,41.84984,3.1265,7,3,...,Entire home/apt,2 baths,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""F...",60.0,t,01/04/2023,01/07/2013,18/02/2018,HUTG-017955,f
9,9,1222762,2.02303E+13,6404885,1,1,42.21904,2.90744,5,3,...,Entire home/apt,2 baths,"[""Heating"", ""Kitchen"", ""Air conditioning"", ""Wa...",65.0,t,31/03/2023,19/08/2013,14/09/2022,HUTG-012585,f
11,11,48764,2.02303E+13,220145,1,2,42.17605,3.03974,8,4,...,Entire home/apt,2 baths,"[""Refrigerator"", ""Long term stays allowed"", ""S...",120.0,t,31/03/2023,04/06/2011,13/08/2022,HUTG-000207,f
14,14,1228453,2.02303E+13,6623729,1,1,42.24287,3.20562,5,2,...,Entire home/apt,2 baths,"[""Beach essentials"", ""Board games"", ""Carbon mo...",114.0,t,01/04/2023,12/05/2018,01/01/2023,HUTG-031144,t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19642,19641,858000000000000000.0,20230300000000.0,173153149,51.0,74.0,41.701663,2.870586,6,3.0,...,Entire home/apt,3 baths,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",440.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-023596,t
19643,19642,858000000000000000.0,20230300000000.0,507641932,1.0,1.0,42.1817,3.10666,8,4.0,...,Entire home/apt,4 baths,"[""Air conditioning"", ""Carbon monoxide alarm"", ...",450.0,t,01/04/2023,23/03/2023,26/03/2023,HUTB-449108,f
19644,19643,858000000000000000.0,20230300000000.0,419014196,1.0,2.0,42.366939,3.161534,5,2.0,...,Entire home/apt,2.5 baths,"[""Air conditioning"", ""Beach essentials"", ""Boar...",100.0,t,01/04/2023,23/03/2023,26/03/2023,Exempt,f
19648,19647,858000000000000000.0,20230300000000.0,497533696,25.0,26.0,41.99906,3.19485,5,3.0,...,Entire home/apt,2 baths,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",136.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-037880,t
19651,19650,858000000000000000.0,20230300000000.0,26281633,34.0,44.0,41.957265,3.201288,8,4.0,...,Entire home/apt,5 baths,"[""Pets allowed"", ""Smoking allowed"", ""Essentials""]",209.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-001292,t

In [51]:
#Corroborar el filtro
filtroe['bathrooms_text'].unique()

array(['1.5 shared baths', '2 baths', '4 baths', '4.5 baths', '2.5 baths',
       '3 baths', '6.5 baths', '1 shared bath', '1.5 baths', '3.5 baths',
       '3 shared baths', '7.5 baths', '6 baths', '8 baths', '5 baths',
       '7 baths', '8.5 baths', '10 baths', '5.5 baths',
       '2.5 shared baths', '5 shared baths', nan, '11 baths', '9.5 baths',
       '2 shared baths', '0 baths', '0 shared baths', '9 baths',
       '12 baths', 'Half-bath', '3.5 shared baths', '13 baths',
       '18 baths', '15.5 baths', '10.5 baths', '5.5 shared baths',
       'Shared half-bath', '15 baths', '100 baths', '11.5 baths',
       '6 shared baths', '14.5 baths', '13.5 baths', '14 baths'],
      dtype=object)

In [52]:
filtroe.to_csv("filtroe_ESP.csv")
from google.colab import files 
files.download("filtroe_ESP.csv")

### **f) Los registros cuyo precio sea mayor de $10,000 y que sean de tipo “Entire home”**

In [53]:
filtrof = esp[(esp["price"] > 10000) & (esp["room_type"] == "Entire home/apt")]
filtrof

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
753,753,4682669,2.02303E+13,24213114,2,2,42.053955,3.162875,5,2.2,...,Entire home/apt,8 baths,"[""Beach essentials"", ""Board games"", ""Free park...",12986.0,t,01/04/2023,28/12/2015,26/12/2022,PG-000878,f
1841,1840,11716662,2.02303E+13,10222076,1,1,41.89213,3.1846,4,3,...,Entire home/apt,1.5 baths,"[""Changing table"", ""Fireplace guards"", ""Pack â...",14500.0,t,01/04/2023,14/07/2016,28/08/2022,HUTG-043827,f
3372,3371,17726281,2.02303E+13,120856433,1,1,42.05615,2.64295,6,3,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Free parking on premises...",12977.0,t,31/03/2023,05/04/2017,12/03/2023,HUTG-025778,f
3932,3931,18928661,2.02303E+13,129837136,28,73,41.84915,3.05936,6,3,...,Entire home/apt,2 baths,"[""Sound system"", ""Refrigerator"", ""Valley view""...",20000.0,t,01/04/2023,23/05/2018,01/11/2022,HUTG-008573,t
3949,3948,18928673,2.02303E+13,129837136,28,73,41.85659,3.04899,9,4,...,Entire home/apt,3.5 baths,"[""Sound system"", ""Refrigerator"", ""Microwave"", ...",20000.0,t,01/04/2023,28/05/2017,12/03/2023,HUTG-008208,t
6633,6632,26118654,2.02303E+13,122175936,27.9,34.7,42.28924,3.17472,8,4,...,Entire home/apt,3 baths,"[""Dedicated workspace"", ""Kitchen"", ""Air condit...",16380.0,t,01/04/2023,30/06/2018,30/07/2022,HUTG-013538,t
6651,6650,26146284,2.02303E+13,122175936,27.9,34.7,42.29,3.17656,5,2.2,...,Entire home/apt,4 baths,"[""Dedicated workspace"", ""Kitchen"", ""Air condit...",16380.0,t,01/04/2023,29/08/2020,29/08/2020,HUTG-013538,t
7148,7147,28483889,2.02303E+13,122175936,27.9,34.7,42.28965,3.17508,4,2,...,Entire home/apt,1 bath,"[""Dedicated workspace"", ""Kitchen"", ""Air condit...",16380.0,t,01/04/2023,02/01/2019,22/03/2023,HUTG-013538,t
7542,7541,31969327,2.02303E+13,129837136,28,73,41.86232,3.07854,8,4,...,Entire home/apt,3 baths,"[""Harbor view"", ""Refrigerator"", ""Valley view"",...",20000.0,t,01/04/2023,10/06/2019,19/08/2022,HUTG-029082,t
9978,9977,41784831.0,20230300000000.0,270230553,27.9,34.7,42.1936,3.02802,8,4.0,...,Entire home/apt,3 baths,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",15960.0,t,31/03/2023,28/06/2020,05/09/2021,HUTG/028780,t

In [54]:
filtrof.to_csv("filtrof_ESP.csv")
from google.colab import files 
files.download("filtrof_ESP.csv")

### **g) Los registros cuyo review_scores_cleanliness > 4.5**

In [55]:
filtrog = esp[esp['review_scores_cleanliness'] > 4.5]
filtrog

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,14551,2.02303E+13,57237,1,5,41.9965,2.83646,2,1,...,Private room,1 private bath,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",42.0,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
1,1,1205757,2.02303E+13,6586355,1,1,41.79304,2.77412,2,1,...,Private room,1.5 shared baths,"[""Free parking on premises"", ""Refrigerator"", ""...",47.0,t,31/03/2023,01/08/2013,26/06/2022,HUTG-049542,f
4,4,41342,2.02303E+13,180072,2,3,42.34655,3.20463,4,1,...,Entire home/apt,1 bath,"[""Free parking on premises"", ""Refrigerator"", ""...",120.0,t,01/04/2023,14/07/2013,28/08/2021,HUTG-003688,f
5,5,751997,2.02303E+13,3387407,12,12,41.91798,3.16419,4,1,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Pack ân play/Travel cr...",105.0,t,01/04/2023,03/05/2016,26/02/2023,HUTG-016218,t
6,6,752035,2.02303E+13,3387407,12,12,41.91801,3.17085,4,2,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",110.0,t,31/03/2023,02/07/2013,31/10/2021,HUTG-008974,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18986,18985,843000000000000000.0,20230300000000.0,3205684,1.0,1.0,41.69662,2.82711,2,1.0,...,Entire home/apt,1 bath,"[""Kitchen"", ""Air conditioning"", ""Shared pool"",...",60.0,t,01/04/2023,26/03/2023,26/03/2023,HUTG-020973,t
19002,19001,841000000000000000.0,20230300000000.0,192741333,1.0,1.0,41.72051,2.93222,4,1.0,...,Entire home/apt,1 bath,"[""Stainless steel oven"", ""Refrigerator"", ""Outd...",106.0,t,01/04/2023,20/03/2023,20/03/2023,HUTG-048774,t
19047,19046,842000000000000000.0,20230300000000.0,253595964,2.0,2.0,42.252803,3.105931,4,1.0,...,Entire home/apt,1 bath,"[""Carbon monoxide alarm"", ""Free parking on pre...",59.0,t,01/04/2023,26/03/2023,26/03/2023,Exempt,t
19078,19077,842000000000000000.0,20230300000000.0,38726312,2.0,2.0,42.24757,3.10449,2,1.0,...,Private room,1 shared bath,"[""Hair dryer"", ""Dedicated workspace"", ""Air con...",39.0,t,01/04/2023,15/03/2023,15/03/2023,HUTG-047773,f
19203,19202,843000000000000000.0,20230300000000.0,121671158,1.0,3.0,42.246529,3.127426,4,1.0,...,Entire home/apt,1 bath,"[""Central air conditioning"", ""Refrigerator"", ""...",80.0,t,01/04/2023,12/03/2023,17/03/2023,HUTG-027175,f

In [56]:
#Corroborar el filtro
filtrog['review_scores_cleanliness'].unique()

array([4.94, 4.85, 4.82, 4.69, 4.79, 4.78, 4.73, 4.95, 4.88, 4.55, 5.  ,
       4.76, 4.96, 4.6 , 4.65, 4.84, 4.87, 4.72, 4.81, 4.91, 4.64, 4.8 ,
       4.67, 4.74, 4.9 , 4.71, 4.75, 4.54, 4.68, 4.57, 4.77, 4.51, 4.59,
       4.66, 4.93, 4.52, 4.58, 4.61, 4.7 , 4.53, 4.92, 4.56, 4.89, 4.97,
       4.83, 4.98, 4.86, 4.63, 4.62, 4.99])

In [57]:
filtrog.to_csv("filtrog_ESP.csv")
from google.colab import files 
files.download("filtrog_ESP.csv")

### **h) Los registros cuyo review_scores_value > 4.9**

In [58]:
filtroh = esp[esp['review_scores_value'] > 4.9]
filtroh

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
22,22,1234785,2.02303E+13,6732502,2,2,41.95188,3.20297,6,3,...,Entire home/apt,2.5 baths,"[""Shared pool"", ""Free parking on premises"", ""R...",335.0,t,01/04/2023,30/08/2021,25/08/2022,HUTG-026895,f
26,26,774371,2.02303E+13,4085536,2,2,41.84428,3.10006,5,2,...,Entire home/apt,2 baths,"[""Central air conditioning"", ""Refrigerator"", ""...",60.0,t,01/04/2023,22/01/2017,10/09/2022,HUTG-014853,f
40,40,1250062,2.02303E+13,6811852,1,1,41.82205,3.06874,8,4,...,Entire home/apt,2.5 baths,"[""Shared pool"", ""Courtyard view"", ""Free parkin...",303.0,t,01/04/2023,03/08/2021,21/07/2022,HUTG-025234,f
43,43,809136,2.02303E+13,4208003,35,72,42.10369,3.0823,4,2,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Refrigerator"", ""Microwav...",108.0,t,31/03/2023,09/04/2015,01/06/2019,HUTG-001370,t
53,53,1262051,2.02303E+13,6595329,7,7,42.20932,2.73697,4,1,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",73.0,t,31/03/2023,01/05/2016,04/11/2018,ATG-000053,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19039,19038,841000000000000000.0,20230300000000.0,232395755,2.0,3.0,42.340474,3.0,2,1.0,...,Entire home/apt,1 bath,"[""Free parking on premises"", ""Refrigerator"", ""...",70.0,t,31/03/2023,26/03/2023,26/03/2023,HUTG-063362,f
19047,19046,842000000000000000.0,20230300000000.0,253595964,2.0,2.0,42.252803,3.105931,4,1.0,...,Entire home/apt,1 bath,"[""Carbon monoxide alarm"", ""Free parking on pre...",59.0,t,01/04/2023,26/03/2023,26/03/2023,Exempt,t
19078,19077,842000000000000000.0,20230300000000.0,38726312,2.0,2.0,42.24757,3.10449,2,1.0,...,Private room,1 shared bath,"[""Hair dryer"", ""Dedicated workspace"", ""Air con...",39.0,t,01/04/2023,15/03/2023,15/03/2023,HUTG-047773,f
19203,19202,843000000000000000.0,20230300000000.0,121671158,1.0,3.0,42.246529,3.127426,4,1.0,...,Entire home/apt,1 bath,"[""Central air conditioning"", ""Refrigerator"", ""...",80.0,t,01/04/2023,12/03/2023,17/03/2023,HUTG-027175,f
19468,19467,850000000000000000.0,20230300000000.0,505978243,1.0,1.0,41.974072,2.789637,3,1.0,...,Private room,1 shared bath,"[""Dedicated workspace"", ""Mountain view"", ""Iron...",22.0,t,01/04/2023,23/03/2023,26/03/2023,HUTS-201920,t

In [59]:
#Corroborar el filtro
filtroh['review_scores_value'].unique()

array([5.  , 4.92, 4.94, 4.93, 4.95, 4.91, 4.96, 4.98, 4.97])

In [60]:
filtroh.to_csv("filtroh_ESP.csv")
from google.colab import files 
files.download("filtroh_ESP.csv")

### **i) Los registros cuya availability_365< 100**

In [61]:
esp.availability_365 = esp.availability_365.replace({'HUTG000237':'0'}, regex=False)

In [62]:
esp.availability_365 = esp.availability_365.astype(int)

In [63]:
filtroi=esp[esp['availability_365'] < 100]
filtroi

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
4,4,41342,2.02303E+13,180072,2,3,42.34655,3.20463,4,1,...,Entire home/apt,1 bath,"[""Free parking on premises"", ""Refrigerator"", ""...",120.0,t,01/04/2023,14/07/2013,28/08/2021,HUTG-003688,f
7,7,1215790,2.02303E+13,3149645,1,1,41.84984,3.1265,7,3,...,Entire home/apt,2 baths,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""F...",60.0,t,01/04/2023,01/07/2013,18/02/2018,HUTG-017955,f
11,11,48764,2.02303E+13,220145,1,2,42.17605,3.03974,8,4,...,Entire home/apt,2 baths,"[""Refrigerator"", ""Long term stays allowed"", ""S...",120.0,t,31/03/2023,04/06/2011,13/08/2022,HUTG-000207,f
15,15,93343,2.02303E+13,477826,4,6,42.10405,3.14936,7,3,...,Entire home/apt,2 baths,"[""Air conditioning"", ""Free parking on premises...",173.0,t,01/04/2023,12/05/2018,01/01/2023,HUTG-001447,f
20,20,1234784,2.02303E+13,6732502,2,2,41.95156,3.20217,2,1,...,Private room,1 private bath,"[""Shared pool"", ""Shampoo"", ""Host greets you"", ...",80.0,t,01/04/2023,08/07/2013,13/06/2021,HUTG-026895,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19628,19627,858000000000000000.0,20230300000000.0,127955218,79.0,142.0,41.866532,3.069004,6,3.0,...,Entire home/apt,3 baths,"[""Air conditioning"", ""Refrigerator"", ""Bidet"", ...",362.0,t,31/03/2023,23/03/2023,26/03/2023,HUTG-036943,t
19633,19632,858000000000000000.0,20230300000000.0,127955218,79.0,142.0,41.779129,3.028061,6,3.0,...,Entire home/apt,2 baths,"[""Air conditioning"", ""Free parking on premises...",349.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-000001,t
19635,19634,858000000000000000.0,20230300000000.0,21668566,69.0,72.0,42.357181,3.167029,4,2.0,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Free parking on premises...",108.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-068543,t
19639,19638,858000000000000000.0,20230300000000.0,461023346,10.0,10.0,41.973,3.17423,6,3.0,...,Entire home/apt,2 baths,"[""Mountain view"", ""Kitchen"", ""Washer"", ""BBQ gr...",160.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-006876,f
19655,19654,858000000000000000.0,20230300000000.0,491503593,9.0,11.0,41.810169,3.066358,5,3.0,...,Entire home/apt,1 bath,"[""Kitchen"", ""Washer"", ""Clothing storage"", ""Dis...",73.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-051787,f

In [64]:
#Corroborar el filtro
filtroi['availability_365'].unique()

array([ 0, 56, 28, 84, 10,  1, 94, 47,  9, 88, 51, 90, 86, 25, 69, 29, 76,
       80, 77, 70, 91, 65, 72, 87, 46, 67, 89, 27, 19, 79, 38, 83, 92, 82,
       53, 15, 35, 95, 42, 50, 31, 45, 57, 73, 41, 34, 44, 85, 13, 43, 14,
       99, 24, 54,  4, 36, 75, 16, 93, 96, 78, 63, 52, 17,  8, 74, 81, 12,
       21, 64, 98, 60, 61, 40,  6, 58, 59, 32, 97, 30,  7, 62, 18, 23, 37,
       71, 68, 48,  5, 20, 33,  2, 22, 11, 55, 49, 66, 26,  3, 39])

In [65]:
filtroi.to_csv("filtroi_ESP.csv")
from google.colab import files 
files.download("filtroi_ESP.csv")

### **j) Los registros cuya host_response_time sea “within an hour”**

In [66]:
filtroj = esp[esp["host_response_time"] == "within an hour"]
filtroj

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
0,0,14551,2.02303E+13,57237,1,5,41.9965,2.83646,2,1,...,Private room,1 private bath,"[""Shared pool"", ""Refrigerator"", ""Long term sta...",42.0,t,31/03/2023,08/10/2010,27/02/2023,HUTG-049542,f
5,5,751997,2.02303E+13,3387407,12,12,41.91798,3.16419,4,1,...,Entire home/apt,1 bath,"[""Air conditioning"", ""Pack ân play/Travel cr...",105.0,t,01/04/2023,03/05/2016,26/02/2023,HUTG-016218,t
6,6,752035,2.02303E+13,3387407,12,12,41.91801,3.17085,4,2,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",110.0,t,31/03/2023,02/07/2013,31/10/2021,HUTG-008974,f
7,7,1215790,2.02303E+13,3149645,1,1,41.84984,3.1265,7,3,...,Entire home/apt,2 baths,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""F...",60.0,t,01/04/2023,01/07/2013,18/02/2018,HUTG-017955,f
8,8,45400,2.02303E+13,201228,1,2,41.95577,3.21096,4,1,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Washer"", ""E...",83.0,t,01/04/2023,28/12/2010,04/03/2023,HUTG-015895,t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19649,19648,858000000000000000.0,20230300000000.0,13308911,51.0,59.0,41.72036,2.92986,4,1.0,...,Entire home/apt,1 bath,"[""Hair dryer"", ""Kitchen"", ""Iron"", ""Air conditi...",107.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-027601,t
19650,19649,858000000000000000.0,20230300000000.0,507731324,1.0,1.0,42.24504,3.12588,4,1.0,...,Entire home/apt,1 bath,"[""TV"", ""Kitchen""]",75.0,t,01/04/2023,23/03/2023,26/03/2023,Exempt,t
19651,19650,858000000000000000.0,20230300000000.0,26281633,34.0,44.0,41.957265,3.201288,8,4.0,...,Entire home/apt,5 baths,"[""Pets allowed"", ""Smoking allowed"", ""Essentials""]",209.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-001292,t
19652,19651,858000000000000000.0,20230300000000.0,444428600,3.0,3.0,41.69907,2.84408,4,1.0,...,Entire home/apt,1 bath,"[""Kitchen"", ""Pets allowed"", ""Washer""]",52.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG019727,t
19654,19653,858000000000000000.0,20230300000000.0,389605038,111.0,121.0,41.809375,3.05391,4,2.0,...,Entire home/apt,1 bath,"[""Refrigerator"", ""Microwave"", ""Elevator"", ""Pet...",108.0,t,01/04/2023,23/03/2023,26/03/2023,HUTG-065236,t

In [67]:
#Corroborar el filtro
filtroj['host_response_time'].unique()

array(['within an hour'], dtype=object)

In [68]:
filtroj.to_csv("filtroj_ESP.csv")
from google.colab import files 
files.download("filtroj_ESP.csv")