<a href="https://colab.research.google.com/github/RuthMaya/Evaluaci-n/blob/main/MEX_ACTIVIDAD_5_(Evaluaci%C3%B3n)_PARTE_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **ACTIVIDAD 5 (Evaluación) PARTE 2**
## **Ruth Maya López**
## **A01707467**

In [ ]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## **MEX**

In [ ]:
mex = pd.read_csv("Datos_limpios_MEX.csv", low_memory=False)

In [ ]:
mex.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17517 entries, 0 to 17516
Data columns (total 72 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Unnamed: 0                                    17515 non-null  float64
 1   id                                            17517 non-null  object
 2   scrape_id                                     17517 non-null  object
 3   host_id                                       17517 non-null  object
 4   host_listings_count                           17517 non-null  object
 5   host_total_listings_count                     17517 non-null  object
 6   latitude                                      17517 non-null  object
 7   longitude                                     17517 non-null  object
 8   accommodates                                  17517 non-null  object
 9   bedrooms                                      17517 non-null  object
 10  beds                                          17517 non-null  object
 11  minimum_nights                                17517 non-null  object
 12  maximum_nights                                17517 non-null  object
 13  minimum_minimum_nights                        17517 non-null  object
 14  maximum_minimum_nights                        17517 non-null  object
 15  minimum_maximum_nights                        17517 non-null  object
 16  maximum_maximum_nights                        17517 non-null  object
 17  minimum_nights_avg_ntm                        17517 non-null  object
 18  maximum_nights_avg_ntm                        17517 non-null  object
 19  availability_30                               17517 non-null  object
 20  availability_60                               17517 non-null  object
 21  availability_90                               17517 non-null  object
 22  availability_365                              17517 non-null  object
 23  number_of_reviews                             17515 non-null  float64
 24  number_of_reviews_ltm                         17515 non-null  float64
 25  number_of_reviews_l30d                        17515 non-null  float64
 26  review_scores_rating                          17515 non-null  float64
 27  review_scores_accuracy                        17515 non-null  float64
 28  review_scores_cleanliness                     17515 non-null  float64
 29  review_scores_checkin                         17515 non-null  float64
 30  review_scores_communication                   17515 non-null  float64
 31  review_scores_location                        17515 non-null  float64
 32  review_scores_value                           17515 non-null  float64
 33  calculated_host_listings_count                17515 non-null  float64
 34  calculated_host_listings_count_entire_homes   17515 non-null  float64
 35  calculated_host_listings_count_private_rooms  17515 non-null  float64
 36  calculated_host_listings_count_shared_rooms   17515 non-null  float64
 37  reviews_per_month                             17515 non-null  float64
 38  listing_url                                   17515 non-null  object
 39  last_scraped                                  17515 non-null  object
 40  source                                        17515 non-null  object
 41  name                                          17515 non-null  object
 42  description                                   17515 non-null  object
 43  neighborhood_overview                         17515 non-null  object
 44  picture_url                                   17515 non-null  object
 45  host_url                                      17515 non-null  object
 46  host_name                                     17515 non-null  object
 47  host_since                                    17515 non-null  object
 48  host_location                                 17515 non-null  object
 49  host_about                                    17515 non-null  object
 50  host_response_time                            17513 non-null  object
 51  host_response_rate                            17513 non-null  float64
 52  host_acceptance_rate                          17513 non-null  float64
 53  host_is_superhost                             17513 non-null  object
 54  host_thumbnail_url                            17513 non-null  object
 55  host_picture_url                              17513 non-null  object
 56  host_neighbourhood                            17513 non-null  object
 57  host_verifications                            17513 non-null  object
 58  host_has_profile_pic                          17513 non-null  object
 59  host_identity_verified                        17513 non-null  object
 60  neighbourhood                                 17513 non-null  object
 61  neighbourhood_cleansed                        17513 non-null  object
 62  property_type                                 17513 non-null  object
 63  room_type                                     17513 non-null  object
 64  bathrooms_text                                17513 non-null  object
 65  amenities                                     17513 non-null  object
 66  price                                         17513 non-null  float64
 67  has_availability                              17513 non-null  object
 68  calendar_last_scraped                         17513 non-null  object
 69  first_review                                  17513 non-null  object
 70  last_review                                   17513 non-null  object
 71  instant_bookable                              17512 non-null  object
dtypes: float64(19), object(53)
memory usage: 9.6+ MB

### **a) host_acceptance_rate> 50%**

In [ ]:
filtroa=mex[mex['host_acceptance_rate'] > 50]
filtroa

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,0.0,2056638,2.02303E+13,10531228,3,7,19.35353,-99.16299,3,1,...,Entire loft,Entire home/apt,1.5 baths,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",1434.0,t,30/03/23,03/01/14,24/06/18,f
1,1.0,2072354,2.02303E+13,16840050,3,3,19.35358,-99.16948,2,1,...,Entire guest suite,Entire home/apt,1 bath,"[""Free street parking"", ""Cleaning products"", ""...",830.0,t,30/03/23,01/01/14,04/11/22,f
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
3,3.0,35797,2.02303E+13,153786,1,1,19.38283,-99.2,2,1,...,Entire villa,Entire home/apt,1 bath,"[""Wifi"", ""Washer"", ""BBQ grill"", ""Indoor firepl...",3658.0,t,29/03/23,31/10/12,21/12/22,f
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17512,17510.0,6.55749E+17,2.02303E+13,10764020,5.3,6.2,19.41952,-99.17669,4,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wine glasses"", ""Cleaning prod...",1402.0,t,29/03/23,31/07/22,18/03/23,t
17513,17511.0,6.53905E+17,2.02303E+13,460400195,1,1,19.45228,-99.13943,2,1,...,Private room in rental unit,Private room,1 private bath,"[""Free street parking"", ""Hot water kettle"", ""L...",400.0,t,29/03/23,26/06/22,12/03/23,t
17514,17512.0,6.53997E+17,2.02303E+13,257853661,15,15,19.36185,-99.2,4,1,...,Entire loft,Entire home/apt,1 bath,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",1124.0,t,29/03/23,03/07/22,09/03/23,t
17515,17513.0,6.55753E+17,2.02303E+13,23021265,13,14,19.40904853,-99.16711839,1,1,...,Private room in rental unit,Private room,1 shared bath,"[""Stainless steel oven"", ""Free street parking""...",570.0,t,29/03/23,31/07/22,27/01/23,f
17516,17514.0,6.54191E+17,2.02303E+13,22442781,1,1,19.431,-99.19494,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Free washer \u2013 In unit"", ""Iron"", ""Pets a...",1143.0,t,30/03/23,20/07/22,0,NaN

In [ ]:
#Corroborar el filtro
filtroa['host_acceptance_rate'].unique()

array([ 90.,  86.,  70.,  95., 100.,  58.,  98.,  73.,  87.,  99.,  77.,
        75.,  97.,  94.,  81.,  89.,  60.,  91.,  92.,  85.,  93.,  71.,
        88.,  82.,  64.,  74.,  63.,  67.,  96.,  83.,  80.,  59.,  68.,
        76.,  65.,  66.,  69.,  54.,  78.,  84.,  56.,  53.,  79.,  52.,
        57.,  72.,  61.,  62.,  55.])

In [ ]:
filtroa.to_csv("filtroa_MEX.csv")
from google.colab import files 
files.download("filtroa_MEX.csv")

### **b) Sólo los registros con categoría “superhost”**

In [ ]:
#Filtro por objeto 
filtrob=mex[mex["host_is_superhost"] == "t"]
filtrob

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
6,6.0,56074,2.02303E+13,265650,2,6,19.43977,-99.15605,2,1,...,Entire condo,Entire home/apt,1 bath,"[""Luggage dropoff allowed"", ""Long term stays a...",650.0,t,29/03/23,02/04/11,21/01/23,f
7,7.0,61792,2.02303E+13,299558,2,3,19.41083,-99.18057,2,1,...,Private room in home,Private room,1 shared bath,"[""Heating - split type ductless system"", ""Whir...",1089.0,t,30/03/23,01/11/17,31/12/22,f
8,8.0,704779,2.02303E+13,2872228,13,14,19.43103,-99.14661,2,1,...,Entire condo,Entire home/apt,1 bath,"[""Ethernet connection"", ""TV with standard cabl...",943.0,t,29/03/23,21/08/13,27/02/23,f
9,9.0,728372,2.02303E+13,3777702,6,7,19.44222,-99.14461,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""TV with standard cabl...",2561.0,t,29/03/23,31/10/12,17/02/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17507,17505.0,6.53875E+17,2.02303E+13,104953556,5.3,6.2,19.4183364,-99.1613886,2.9,1.4,...,Entire home,Entire home/apt,3 baths,"[""Luggage dropoff allowed"", ""Long term stays a...",7708.0,t,30/03/23,28/06/22,25/03/23,f
17510,17508.0,6.51284E+17,2.02303E+13,403848214,5.3,6.2,19.4286725,-99.1616682,2,1,...,Entire rental unit,Entire home/apt,1.5 baths,"[""Ethernet connection"", ""MABE stainless steel ...",1713.0,t,30/03/23,03/07/22,23/03/23,t
17511,17509.0,6.51307E+17,2.02303E+13,453255461,10,10,19.4564,-99.2,2,1,...,Entire loft,Entire home/apt,1 bath,"[""Wifi"", ""Iron"", ""Self check-in"", ""Dishes and ...",615.0,t,29/03/23,10/07/22,26/03/23,f
17512,17510.0,6.55749E+17,2.02303E+13,10764020,5.3,6.2,19.41952,-99.17669,4,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wine glasses"", ""Cleaning prod...",1402.0,t,29/03/23,31/07/22,18/03/23,t
17513,17511.0,6.53905E+17,2.02303E+13,460400195,1,1,19.45228,-99.13943,2,1,...,Private room in rental unit,Private room,1 private bath,"[""Free street parking"", ""Hot water kettle"", ""L...",400.0,t,29/03/23,26/06/22,12/03/23,t

In [ ]:
#Corroborar el filtro
filtrob['host_is_superhost'].unique()

array(['t'], dtype=object)

In [ ]:
filtrob.to_csv("filtrob_MEX.csv")
from google.colab import files 
files.download("filtrob_MEX.csv")

### **c) Los registros que no hallan verificado identidad “ not identity_verified”**

In [ ]:
#Filtro por objeto 
filtroc=mex[mex["host_identity_verified"] == "f"]
filtroc

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,0.0,2056638,2.02303E+13,10531228,3,7,19.35353,-99.16299,3,1,...,Entire loft,Entire home/apt,1.5 baths,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",1434.0,t,30/03/23,03/01/14,24/06/18,f
21,21.0,131610,2.02303E+13,647454,3,4,19.35416,-99.16488,2,1,...,Private room,Private room,1 private bath,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",1244.0,t,29/03/23,06/09/14,29/01/23,f
61,61.0,276504,2.02303E+13,1444589,1,1,19.38061,-99.12729,2,1.6,...,Entire rental unit,Entire home/apt,1 bath,"[""Elevator"", ""Wifi"", ""Washer"", ""Kitchen"", ""Poo...",1815.0,f,30/03/23,01/01/12,25/01/21,f
68,68.0,291804,2.02303E+13,1511568,1,1,19.36305,-99.15412,1,1,...,Private room in rental unit,Private room,1 bath,"[""Kitchen"", ""Smoking allowed"", ""Dryer"", ""Washer""]",545.0,t,30/03/23,12/08/13,13/03/23,f
70,70.0,298873,2.02303E+13,1539548,1,3,19.43358,-99.14452,4,2,...,Entire rental unit,Entire home/apt,2 baths,"[""Elevator"", ""Wifi"", ""Oven"", ""Iron"", ""Washer"",...",1362.0,t,30/03/23,19/04/12,03/11/19,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17349,17347.0,6.44149E+17,2.02303E+13,228573278,1,2,19.38423,-99.17677,1,1,...,Private room in condo,Private room,1 shared bath,"[""Ethernet connection"", ""Luggage dropoff allow...",307.0,t,29/03/23,13/06/22,27/03/23,t
17358,17356.0,6.44199E+17,2.02303E+13,102944480,1,2,19.4,-99.2,5,1,...,Hut,Entire home/apt,1 bath,"[""BBQ grill"", ""Indoor fireplace"", ""Fire pit"", ...",780.0,t,29/03/23,27/06/22,23/07/22,f
17377,17375.0,6.47862E+17,2.02303E+13,463917774,1,1,19.38746441,-99.19520467,4,2,...,Entire condo,Entire home/apt,2 baths,"[""Wifi"", ""Iron"", ""Washer"", ""Private gym in bui...",1200.0,t,29/03/23,18/08/22,23/03/23,f
17482,17480.0,6.50716E+17,2.02303E+13,462574140,1,1,19.4,-99.1776309,2,1.4,...,Room in aparthotel,Private room,4 shared baths,"[""Wifi"", ""Paid parking on premises"", ""Washer"",...",1000.0,t,29/03/23,03/07/22,03/07/22,t
17491,17489.0,6.53782E+17,2.02303E+13,452016962,1,1,19.4320559,-99.1643403,2,1,...,Entire rental unit,Entire home/apt,1.5 baths,"[""Dedicated workspace"", ""Cooking basics"", ""Iro...",850.0,t,30/03/23,06/08/22,19/11/22,f

In [ ]:
#Corroborar el filtro
filtroc['host_identity_verified'].unique()

array(['f'], dtype=object)

In [ ]:
filtroc.to_csv("filtroc_MEX.csv")
from google.colab import files 
files.download("filtroc_MEX.csv")

### **d) Los registro cuyo property_type = “Private room” y “Hotel room”**

In [ ]:
mex["property_type"].unique()

array(['Entire loft', 'Entire guest suite', 'Entire rental unit',
       'Entire villa', 'Entire home', 'Entire condo',
       'Private room in home', 'Room in serviced apartment',
       'Entire serviced apartment', 'Private room in rental unit',
       'Private room', 'Tiny home', 'Private room in townhouse',
       'Private room in condo', 'Private room in guest suite',
       'Private room in bed and breakfast', 'Entire guesthouse',
       'Private room in guesthouse', 'Private room in serviced apartment',
       'Shared room in rental unit', 'Room in boutique hotel',
       'Entire bungalow', 'Casa particular', 'Private room in tiny home',
       'Private room in loft', 'Entire townhouse', 'Shared room in condo',
       'Shared room in home', 'Shared room in guesthouse',
       'Room in bed and breakfast', 'Entire cabin',
       'Shared room in hostel', 'Private room in farm stay',
       'Private room in floor', 'Shared room in guest suite',
       'Room in aparthotel', 'Room in hotel', 'Entire place',
       'Private room in chalet', 'Shared room in serviced apartment',
       'Private room in hostel', 'Earthen home', 'Entire hostel',
       'Private room in villa', 'Private room in bungalow',
       'Private room in casa particular', 'Private room in dorm',
       'Private room in dome', 'Private room in hut', 'Entire chalet',
       'Private room in cabin', 'Shared room in dorm', 'Entire in-law',
       'Holiday park', 'Entire cottage', 'Shared room in loft',
       'Room in hostel', 'Campsite', 'Private room in vacation home',
       'Room in casa particular', nan, 'Castle', 'Private room in barn',
       'Shared room in hotel', 'Entire home/apt',
       'Shared room in casa particular', 'Farm stay',
       'Shared room in boutique hotel', 'Shared room in tiny home',
       'Private room in tent', 'Private room in tipi',
       'Shared room in cabin', 'Private room in tower',
       'Private room in cottage', 'Private room in earthen home', 'Hut',
       'Entire vacation home', 'Shared room in bed and breakfast',
       'Private room in shipping container',
       'Private room in nature lodge', 'Private room in lighthouse',
       'Shared room in vacation home', 'Shared room in townhouse',
       'Shared room', 'Tipi', 'Private room in treehouse', 'Dome',
       'Shipping container'], dtype=object)

In [ ]:
filtrod=mex[(mex["property_type"] == 'Private room') | (mex["property_type"] == "Hotel room")]
filtrod

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
21,21.0,131610,2.02303E+13,647454,3,4,19.35416,-99.16488,2,1,...,Private room,Private room,1 private bath,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",1244.0,t,29/03/23,06/09/14,29/01/23,f
1062,1062.0,12271259,2.02303E+13,2556582,1,1,19.39057309,-99.12979776,2,1,...,Private room,Private room,1 private bath,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",748.0,t,29/03/23,23/05/17,21/11/22,f
2670,2670.0,19639981,2.02303E+13,136125882,1,2,19.34166,-99.15035,1,1,...,Private room,Private room,1 shared bath,"[""Wifi"", ""Breakfast"", ""Washer"", ""Smoking allow...",181.0,t,29/03/23,26/02/23,26/02/23,t
2805,2805.0,20089283,2.02303E+13,142841816,1,1,19.4,-99.2,2,1,...,Private room,Private room,2 shared baths,"[""Elevator"", ""Extra pillows and blankets"", ""Et...",400.0,t,29/03/23,10/08/17,07/03/23,t
3065,3065.0,21067896,2.02303E+13,151816281,2,2,19.45733,-99.21227,2,1,...,Private room,Private room,1 shared bath,"[""Smoke alarm"", ""Shared gym nearby"", ""Luggage ...",600.0,t,30/03/23,12/12/17,13/01/23,f
3257,3257.0,21765818,2.02303E+13,158580118,1,1,19.43487,-99.18768,2,1,...,Private room,Private room,1 private bath,"[""Private entrance"", ""Wifi"", ""Washer"", ""Hanger...",508.0,t,30/03/23,03/12/17,19/03/23,t
3359,3359.0,22230184,2.02303E+13,93911392,28,6.2,19.41364,-99.16292,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Single...",765.0,t,30/03/23,23/12/17,25/03/23,f
3372,3372.0,22247072,2.02303E+13,93911392,28,6.2,19.41538,-99.16064,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""HDTV w...",822.0,t,30/03/23,21/12/17,19/03/23,f
3455,3455.0,22340146,2.02303E+13,115584349,3,3,19.433,-99.14101,2,1,...,Private room,Private room,1 shared bath,"[""Wifi"", ""Luggage dropoff allowed"", ""Dishes an...",375.0,t,30/03/23,02/01/18,27/11/21,f
3571,3571.0,23026367,2.02303E+13,170856978,1,2,19.4369,-99.20763,2,1.6,...,Private room,Private room,1 private bath,"[""Elevator"", ""Smoke alarm"", ""Private entrance""...",1000.0,t,30/03/23,11/02/18,27/03/23,t
3605,3605.0,23100799,2.02303E+13,103716258,1,1,19.43409,-99.13191,2.9,3,...,Private room,Private room,6 baths,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",27435.0,t,29/03/23,23/03/19,31/10/22,t
4303,4303.0,25868032,2.02303E+13,34171966,3,4,19.34903,-99.16493,2,1,...,Private room,Private room,1 private bath,"[""Wifi"", ""Cooking basics"", ""Iron"", ""Washer"", ""...",526.0,t,30/03/23,02/07/18,27/03/23,t
5667,5667.0,31826983,2.02303E+13,185535296,7,10,19.33975,-99.20108,1,1.6,...,Private room,Private room,1 private bath,"[""Wifi"", ""Hangers"", ""Essentials""]",579.0,t,29/03/23,25/02/19,20/05/22,t
6244,6244.0,33051319,2.02303E+13,245350245,4,8,19.44535,-99.2,2.9,1,...,Private room,Private room,1 private bath,"[""Luggage dropoff allowed"", ""Long term stays a...",1757.0,t,29/03/23,24/03/19,27/11/22,t
11129,11127.0,47007658,2.02303E+13,345395010,2,5,19.40288,-99.13481,2,1,...,Private room,Private room,1 private bath,"[""Ethernet connection"", ""Private entrance"", ""W...",320.0,t,30/03/23,29/06/21,27/02/23,t
11921,11919.0,49045093,2.02303E+13,133609729,2,2,19.37162,-99.16179,1,1,...,Private room,Private room,1 shared bath,"[""Lock on bedroom door"", ""Hot water"", ""Essenti...",450.0,t,30/03/23,01/05/22,20/11/22,f
12300,12298.0,50106680,2.02303E+13,290843938,4,5,19.39061,-99.18114,2,1,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Smoke alarm"", ""Hot wa...",339.0,t,29/03/23,05/12/21,23/03/23,f
12713,12711.0,50796337,2.02303E+13,2518152,8,8,19.45877,-99.17539,2,1,...,Private room,Private room,1.5 shared baths,"[""Free street parking"", ""BBQ grill"", ""Luggage ...",750.0,t,29/03/23,20/01/22,20/01/22,t
12842,12840.0,50893960,2.02303E+13,411507264,1,1,19.453215,-99.181328,1,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Private outdoor kitchen"", ""Ho...",1081.0,t,29/03/23,08/11/21,24/02/23,t
12865,12863.0,51164390,2.02303E+13,161016544,2,2,19.41581,-99.16108,1,1,...,Private room,Private room,3.5 shared baths,"[""City skyline view"", ""Long term stays allowed...",364.0,t,30/03/23,06/08/21,25/01/23,t
13675,13673.0,52557368,2.02303E+13,93911392,28,6.2,19.41534,-99.16228,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",640.0,t,30/03/23,17/10/21,12/03/23,f
13676,13674.0,52557770,2.02303E+13,93911392,28,6.2,19.41334,-99.16086,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",733.0,t,30/03/23,15/10/21,26/03/23,f
13682,13680.0,52558024,2.02303E+13,93911392,28,6.2,19.41389,-99.1629,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",712.0,t,30/03/23,14/10/21,19/03/23,f
13715,13713.0,52536577,2.02303E+13,93911392,28,6.2,19.41382,-99.1627,2,1,...,Private room,Private room,1 private bath,"[""Smoke alarm"", ""Free street parking"", ""Hot wa...",739.0,t,30/03/23,14/10/21,28/02/23,f
14806,14804.0,53805586,2.02303E+13,248524358,6,6,19.38331,-99.16172,1,1,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Free street parking"",...",514.0,t,30/03/23,31/08/22,31/08/22,f
14920,14918.0,54106290,2.02303E+13,438593737,4,4,19.3548,-99.16817,2,1,...,Private room,Private room,1 private bath,"[""Wifi"", ""Shower gel"", ""Cleaning available dur...",1491.0,t,30/03/23,12/01/22,26/06/22,t
15032,15030.0,54194769,2.02303E+13,282436180,2,2,19.45267,-99.2,1,3,...,Private room,Private room,1 shared bath,"[""BBQ grill"", ""HDTV with Netflix"", ""Cleaning p...",400.0,t,29/03/23,07/08/22,30/12/22,f
15094,15092.0,54215774,2.02303E+13,439419001,2,2,19.37657,-99.16506,1,1,...,Private room,Private room,1.5 baths,"[""Stainless steel oven"", ""Free street parking""...",450.0,t,30/03/23,04/02/22,03/05/22,f
15359,15357.0,5.53083E+17,2.02303E+13,438593737,4,4,19.3563,-99.16654,2,1,...,Private room,Private room,1 private bath,"[""Wifi"", ""Shower gel"", ""Free street parking"", ...",1491.0,t,30/03/23,10/02/22,13/11/22,t
16018,16016.0,5.88691E+17,2.02303E+13,400461338,4,18,19.37866,-99.16659,2,1,...,Private room,Private room,1 private bath,"[""Free street parking"", ""Luggage dropoff allow...",771.0,t,30/03/23,26/03/22,01/01/23,f
16936,16934.0,6.26031E+17,2.02303E+13,66387078,5.3,32,19.430712,-99.163963,1,1,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Luggage dropoff allow...",243.0,t,29/03/23,23/05/22,10/03/23,t
16937,16935.0,6.26044E+17,2.02303E+13,66387078,5.3,32,19.43176,-99.16445,1,1,...,Private room,Private room,1 shared bath,"[""Ethernet connection"", ""Luggage dropoff allow...",234.0,t,29/03/23,31/05/22,27/02/23,t
17156,17154.0,6.38322E+17,2.02303E+13,283357024,2,3,19.42988014,-99.15309143,2,1,...,Private room,Private room,1 private bath,"[""Laguna Cyprien shampoo"", ""Luggage dropoff al...",3000.0,t,30/03/23,26/06/22,21/03/23,f
17253,17251.0,6.4566E+17,2.02303E+13,463433619,3,4,19.41896,-99.15701,2,1,...,Private room,Private room,1 private bath,"[""Ethernet connection"", ""Smoke alarm"", ""Hot wa...",1800.0,t,30/03/23,18/07/22,18/07/22,f

In [ ]:
#Corroborar el filtro
filtrod['property_type'].unique()

array(['Private room'], dtype=object)

In [ ]:
filtrod.to_csv("filtrod_MEX.csv")
from google.colab import files 
files.download("filtrod_MEX.csv")

### **e) Los registros que cuenten con bathroom > 1**

In [ ]:
mex['bathrooms_text'].unique()

array(['1.5 baths', '1 bath', '2 baths', '5.5 baths', '1 shared bath',
       '1 private bath', '3 baths', '5 baths', '1.5 shared baths',
       '2.5 baths', '4.5 baths', '6 baths', '3.5 baths', '2 shared baths',
       '3 shared baths', '2.5 shared baths', 'Half-bath',
       '8 shared baths', '4 shared baths', '4 baths', '10 baths',
       '16 baths', '3.5 shared baths', '5 shared baths', '7 baths',
       '20 baths', '4.5 shared baths', '0 shared baths', '0 baths',
       '50 baths', '10 shared baths', '8.5 baths', '9 baths', '7.5 baths',
       '11.5 baths', '8 baths', 'Shared half-bath', '14 baths',
       '6 shared baths', '11 baths', '6.5 baths', nan, '15 baths',
       '13 baths', 'Private half-bath', '15 shared baths',
       '12 shared baths', '9.5 baths'], dtype=object)

In [ ]:
filtroe=mex[~(mex["bathrooms_text"] == '1 bath')  & ~(mex["bathrooms_text"] == "1 private bath")]
filtroe

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,0.0,2056638,2.02303E+13,10531228,3,7,19.35353,-99.16299,3,1,...,Entire loft,Entire home/apt,1.5 baths,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",1434.0,t,30/03/23,03/01/14,24/06/18,f
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
5,5.0,2075738,2.02303E+13,2339771,1,2,19.41909,-99.16043,2,1,...,Entire loft,Entire home/apt,2 baths,"[""BBQ grill"", ""Luggage dropoff allowed"", ""TV w...",2561.0,t,29/03/23,05/02/14,27/02/23,f
7,7.0,61792,2.02303E+13,299558,2,3,19.41083,-99.18057,2,1,...,Private room in home,Private room,1 shared bath,"[""Heating - split type ductless system"", ""Whir...",1089.0,t,30/03/23,01/11/17,31/12/22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17507,17505.0,6.53875E+17,2.02303E+13,104953556,5.3,6.2,19.4183364,-99.1613886,2.9,1.4,...,Entire home,Entire home/apt,3 baths,"[""Luggage dropoff allowed"", ""Long term stays a...",7708.0,t,30/03/23,28/06/22,25/03/23,f
17508,17506.0,6.49715E+17,2.02303E+13,254403121,1,1,19.41181464,-99.17203031,4,2,...,Entire condo,Entire home/apt,2 baths,"[""Ethernet connection"", ""Luggage dropoff allow...",1900.0,t,30/03/23,01/11/22,03/01/23,t
17509,17507.0,6.53891E+17,2.02303E+13,87539949,12,19,19.4185363,-99.1567503,4,2,...,Entire condo,Entire home/apt,2 baths,"[""Dedicated workspace"", ""Hair dryer"", ""Wifi"", ...",2253.0,t,30/03/23,30/06/22,15/02/23,t
17510,17508.0,6.51284E+17,2.02303E+13,403848214,5.3,6.2,19.4286725,-99.1616682,2,1,...,Entire rental unit,Entire home/apt,1.5 baths,"[""Ethernet connection"", ""MABE stainless steel ...",1713.0,t,30/03/23,03/07/22,23/03/23,t
17515,17513.0,6.55753E+17,2.02303E+13,23021265,13,14,19.40904853,-99.16711839,1,1,...,Private room in rental unit,Private room,1 shared bath,"[""Stainless steel oven"", ""Free street parking""...",570.0,t,29/03/23,31/07/22,27/01/23,f

In [ ]:
#Corroborar el filtro
filtroe['bathrooms_text'].unique()

array(['1.5 baths', '2 baths', '5.5 baths', '1 shared bath', '3 baths',
       '5 baths', '1.5 shared baths', '2.5 baths', '4.5 baths', '6 baths',
       '3.5 baths', '2 shared baths', '3 shared baths',
       '2.5 shared baths', 'Half-bath', '8 shared baths',
       '4 shared baths', '4 baths', '10 baths', '16 baths',
       '3.5 shared baths', '5 shared baths', '7 baths', '20 baths',
       '4.5 shared baths', '0 shared baths', '0 baths', '50 baths',
       '10 shared baths', '8.5 baths', '9 baths', '7.5 baths',
       '11.5 baths', '8 baths', 'Shared half-bath', '14 baths',
       '6 shared baths', '11 baths', '6.5 baths', nan, '15 baths',
       '13 baths', 'Private half-bath', '15 shared baths',
       '12 shared baths', '9.5 baths'], dtype=object)

In [ ]:
filtroe.to_csv("filtroe_MEX.csv")
from google.colab import files 
files.download("filtroe_MEX.csv")

### **f) Los registros cuyo precio sea mayor de $10,000 y que sean de tipo “Entire home”**

In [ ]:
filtrof = mex[(mex["price"] > 10000) & (mex["room_type"] == "Entire home/apt")]
filtrof

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
37,37.0,187030,2.02303E+13,899360,6,8,19.41057,-99.1773,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",50000.0,t,30/03/23,01/11/11,15/03/23,f
418,418.0,6041044,2.02303E+13,7529413,1,1,19.42898,-99.16885,6,3,...,Entire townhouse,Entire home/apt,5.5 baths,"[""Ethernet connection"", ""Smoke alarm"", ""Fast w...",14000.0,t,30/03/23,04/01/23,20/03/23,f
544,544.0,6871835,2.02303E+13,36014559,1,1,19.39614,-99.17371,2,2,...,Entire rental unit,Entire home/apt,2 baths,"[""Smoke alarm"", ""BBQ grill"", ""Pool"", ""TV with ...",31386.0,t,30/03/23,21/06/15,22/06/17,f
958,958.0,9946549,2.02303E+13,51117526,1,1,19.39196,-99.15615,4,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Wifi"", ""Washer"", ""Kitchen"", ""TV"", ""Essentials""]",17247.0,t,30/03/23,07/02/16,09/03/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16927,16925.0,6.30419E+17,2.02303E+13,459926071,1,1,19.409195,-99.17215,2.9,1.4,...,Entire rental unit,Entire home/apt,5.5 baths,"[""Stainless steel oven"", ""Smoke alarm"", ""Pack ...",10161.0,t,30/03/23,08/08/22,02/10/22,f
16966,16964.0,6.28233E+17,2.02303E+13,418651325,5.3,6.2,19.41152,-99.175415,2.9,1.4,...,Entire home,Entire home/apt,3 baths,"[""Stainless steel oven"", ""Ethernet connection""...",19002.0,t,30/03/23,22/05/22,12/03/23,f
17010,17008.0,6.34356E+17,2.02303E+13,460826213,1,1,19.4,-99.122307,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Washer"", ""Kitchen"", ""TV"", ""Free parking on p...",30000.0,t,29/03/23,02/06/22,24/03/23,f
17034,17032.0,6.34789E+17,2.02303E+13,418651325,5.3,6.2,19.411661,-99.17524,2.9,1.4,...,Entire home,Entire home/apt,6.5 baths,"[""Stainless steel oven"", ""Ethernet connection""...",19913.0,t,30/03/23,17/07/22,05/03/23,f
17121,17119.0,6.2976E+17,2.02303E+13,418651325,5.3,6.2,19.411661,-99.17524,2.9,1.4,...,Entire home,Entire home/apt,3.5 baths,"[""Stainless steel oven"", ""Ethernet connection""...",23011.0,t,30/03/23,10/06/22,15/03/23,f

In [ ]:
filtrof.to_csv("filtrof_MEX.csv")
from google.colab import files 
files.download("filtrof_MEX.csv")

### **g) Los registros cuyo review_scores_cleanliness > 4.5**

In [ ]:
filtrog = mex[mex['review_scores_cleanliness'] > 4.5]
filtrog

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,0.0,2056638,2.02303E+13,10531228,3,7,19.35353,-99.16299,3,1,...,Entire loft,Entire home/apt,1.5 baths,"[""Wifi"", ""Hangers"", ""Fire extinguisher"", ""Sham...",1434.0,t,30/03/23,03/01/14,24/06/18,f
1,1.0,2072354,2.02303E+13,16840050,3,3,19.35358,-99.16948,2,1,...,Entire guest suite,Entire home/apt,1 bath,"[""Free street parking"", ""Cleaning products"", ""...",830.0,t,30/03/23,01/01/14,04/11/22,f
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
3,3.0,35797,2.02303E+13,153786,1,1,19.38283,-99.2,2,1,...,Entire villa,Entire home/apt,1 bath,"[""Wifi"", ""Washer"", ""BBQ grill"", ""Indoor firepl...",3658.0,t,29/03/23,31/10/12,21/12/22,f
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17512,17510.0,6.55749E+17,2.02303E+13,10764020,5.3,6.2,19.41952,-99.17669,4,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wine glasses"", ""Cleaning prod...",1402.0,t,29/03/23,31/07/22,18/03/23,t
17513,17511.0,6.53905E+17,2.02303E+13,460400195,1,1,19.45228,-99.13943,2,1,...,Private room in rental unit,Private room,1 private bath,"[""Free street parking"", ""Hot water kettle"", ""L...",400.0,t,29/03/23,26/06/22,12/03/23,t
17514,17512.0,6.53997E+17,2.02303E+13,257853661,15,15,19.36185,-99.2,4,1,...,Entire loft,Entire home/apt,1 bath,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",1124.0,t,29/03/23,03/07/22,09/03/23,t
17515,17513.0,6.55753E+17,2.02303E+13,23021265,13,14,19.40904853,-99.16711839,1,1,...,Private room in rental unit,Private room,1 shared bath,"[""Stainless steel oven"", ""Free street parking""...",570.0,t,29/03/23,31/07/22,27/01/23,f
17516,17514.0,6.54191E+17,2.02303E+13,22442781,1,1,19.431,-99.19494,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Free washer \u2013 In unit"", ""Iron"", ""Pets a...",1143.0,t,30/03/23,20/07/22,0,NaN

In [ ]:
#Corroborar el filtro
filtrog['review_scores_cleanliness'].unique()

array([4.95, 4.88, 4.71, 4.7 , 4.9 , 4.75, 4.69, 4.96, 4.73, 4.83, 4.8 ,
       4.6 , 5.  , 4.84, 4.91, 4.67, 4.78, 4.92, 4.86, 4.97, 4.59, 4.93,
       4.63, 4.68, 4.65, 4.58, 4.81, 4.72, 4.85, 4.94, 4.89, 4.76, 4.56,
       4.87, 4.82, 4.51, 4.62, 4.77, 4.79, 4.74, 4.66, 4.99, 4.54, 4.98,
       4.57, 4.55, 4.64, 4.61, 4.52, 4.53])

In [ ]:
filtrog.to_csv("filtrog_MEX.csv")
from google.colab import files 
files.download("filtrog_MEX.csv")

### **h) Los registros cuyo review_scores_value > 4.9**

In [ ]:
filtroh = mex[mex['review_scores_value'] > 4.9]
filtroh

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
10,10.0,2083241,2.02303E+13,8282570,7,7,19.4153,-99.16763,3,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",1881.0,t,30/03/23,03/10/14,13/03/23,f
11,11.0,67703,2.02303E+13,334451,3,5,19.41152,-99.16857,4,2,...,Entire rental unit,Entire home/apt,1 bath,"[""Record player"", ""Extra pillows and blankets""...",2088.0,t,30/03/23,17/11/11,01/01/23,f
13,13.0,70644,2.02303E+13,212109,3,4,19.35448,-99.16217,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Free street parking"", ""Luggag...",1097.0,t,29/03/23,14/02/12,31/01/23,f
24,24.0,783080,2.02303E+13,1767559,3,3,19.33009,-99.21418,1,1,...,Private room in home,Private room,1.5 baths,"[""Extra pillows and blankets"", ""Wifi"", ""Iron"",...",549.0,t,29/03/23,26/06/15,26/03/23,f
26,26.0,2118573,2.02303E+13,10802698,3,3,19.38777,-99.17532,6,3,...,Entire rental unit,Entire home/apt,3 baths,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Si...",2049.0,t,30/03/23,31/01/14,02/03/23,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17492,17490.0,6.53811E+17,2.02303E+13,202892955,6,8,19.3705795,-99.1492259,2,1,...,Private room in guest suite,Private room,1.5 baths,"[""Free street parking"", ""HDTV with standard ca...",254.0,t,29/03/23,30/06/22,01/03/23,f
17498,17496.0,6.53834E+17,2.02303E+13,245618000,5.3,6.2,19.34364,-99.2,1,1,...,Private room in serviced apartment,Private room,1 private bath,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Co...",760.0,t,29/03/23,30/06/22,13/08/22,f
17500,17498.0,6.50969E+17,2.02303E+13,309982168,3,3,19.34348,-99.2,2,1,...,Private room in bed and breakfast,Private room,2.5 shared baths,"[""Free street parking"", ""Luggage dropoff allow...",366.0,t,29/03/23,23/07/22,26/02/23,t
17501,17499.0,6.53854E+17,2.02303E+13,123526726,26,32,19.43202,-99.18991,2,1,...,Private room in rental unit,Private room,1 private bath,"[""Dedicated workspace"", ""Hair dryer"", ""Smoke a...",999.0,t,30/03/23,25/10/22,28/03/23,f
17509,17507.0,6.53891E+17,2.02303E+13,87539949,12,19,19.4185363,-99.1567503,4,2,...,Entire condo,Entire home/apt,2 baths,"[""Dedicated workspace"", ""Hair dryer"", ""Wifi"", ...",2253.0,t,30/03/23,30/06/22,15/02/23,t

In [ ]:
#Corroborar el filtro
filtroh['review_scores_value'].unique()

array([4.91, 4.92, 5.  , 4.95, 4.98, 4.94, 4.97, 4.96, 4.93, 4.99])

In [ ]:
filtroh.to_csv("filtroh_MEX.csv")
from google.colab import files 
files.download("filtroh_MEX.csv")

### **i) Los registros cuya availability_365< 100**

In [ ]:
mex.availability_365 = mex.availability_365.replace({'f':'0'}, regex=False)

In [ ]:
mex.availability_365 = mex.availability_365.astype(int)

In [ ]:
filtroi=mex[mex['availability_365'] < 100]
filtroi

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
21,21.0,131610,2.02303E+13,647454,3,4,19.35416,-99.16488,2,1,...,Private room,Private room,1 private bath,"[""Patio or balcony"", ""Wifi"", ""Breakfast"", ""Lug...",1244.0,t,29/03/23,06/09/14,29/01/23,f
26,26.0,2118573,2.02303E+13,10802698,3,3,19.38777,-99.17532,6,3,...,Entire rental unit,Entire home/apt,3 baths,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Si...",2049.0,t,30/03/23,31/01/14,02/03/23,f
37,37.0,187030,2.02303E+13,899360,6,8,19.41057,-99.1773,2,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Ethernet connection"", ""Smoke alarm"", ""Free s...",50000.0,t,30/03/23,01/11/11,15/03/23,f
38,38.0,187745,2.02303E+13,899360,6,8,19.41057,-99.1773,3,1,...,Entire loft,Entire home/apt,2 baths,"[""Wifi"", ""Washer"", ""Free street parking"", ""Hos...",5000.0,t,30/03/23,10/11/13,03/01/18,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17451,17449.0,6.53539E+17,2.02303E+13,462374848,5,7,19.4408677,-99.1855899,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Smoke alarm"", ""Single level home"", ""Long ter...",2166.0,t,30/03/23,25/06/22,01/03/23,t
17467,17465.0,6.53614E+17,2.02303E+13,462374848,5,7,19.4104601,-99.1753482,3,1.6,...,Entire rental unit,Entire home/apt,1 bath,"[""Single level home"", ""Long term stays allowed...",2578.0,t,30/03/23,24/06/22,13/03/23,t
17471,17469.0,6.50698E+17,2.02303E+13,335634100,1,1,19.41276,-99.17708,2,1,...,Entire vacation home,Entire home/apt,1 bath,"[""Heating"", ""Wifi"", ""Patio or balcony"", ""Washe...",900.0,t,30/03/23,29/10/22,26/02/23,f
17472,17470.0,6.49328E+17,2.02303E+13,115584349,3,3,19.43106,-99.14323,2,1,...,Private room in rental unit,Private room,1 shared bath,"[""Wifi"", ""Luggage dropoff allowed"", ""Hot water...",459.0,t,29/03/23,03/07/22,03/07/22,f
17509,17507.0,6.53891E+17,2.02303E+13,87539949,12,19,19.4185363,-99.1567503,4,2,...,Entire condo,Entire home/apt,2 baths,"[""Dedicated workspace"", ""Hair dryer"", ""Wifi"", ...",2253.0,t,30/03/23,30/06/22,15/02/23,t

In [ ]:
#Corroborar el filtro
filtroi['availability_365'].unique()

array([87, 88,  0, 26, 90, 80,  2, 72, 30, 11, 48, 84, 16, 62, 81, 75, 51,
       74, 58, 71, 50, 54, 57, 79, 56, 77, 49, 89, 73, 52, 15, 17, 85, 37,
       61, 83, 63, 32,  3,  1, 33,  8, 70,  6, 40, 39, 23, 53, 18, 27, 86,
       55, 82, 14, 20, 43, 25, 99, 60, 47, 44, 46, 66, 65, 35, 69, 59, 76,
       78, 93, 34, 28, 64, 41,  5, 67, 19, 92, 10, 98, 31,  9, 94, 45, 13,
       24, 22, 21, 29, 36, 91, 42, 38, 12,  4, 97, 96,  7, 68, 95])

In [ ]:
filtroi.to_csv("filtroi_MEX.csv")
from google.colab import files 
files.download("filtroi_MEX.csv")

### **j) Los registros cuya host_response_time sea “within an hour”**

In [ ]:
filtroj = mex[mex["host_response_time"] == "within an hour"]
filtroj

,Unnamed: 0,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,...,property_type,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
2,2.0,696037,2.02303E+13,3531879,4,4,19.4418,-99.18402,6,3,...,Entire rental unit,Entire home/apt,2 baths,"[""Wifi \u2013 38 Mbps"", ""Central air condition...",1469.0,t,29/03/23,31/10/12,21/12/22,f
3,3.0,35797,2.02303E+13,153786,1,1,19.38283,-99.2,2,1,...,Entire villa,Entire home/apt,1 bath,"[""Wifi"", ""Washer"", ""BBQ grill"", ""Indoor firepl...",3658.0,t,29/03/23,31/10/12,21/12/22,f
4,4.0,44616,2.02303E+13,196253,16,16,19.41162,-99.17794,2.9,1.4,...,Entire home,Entire home/apt,5.5 baths,"[""Free street parking"", ""Security cameras on p...",18000.0,t,30/03/23,09/11/11,26/03/23,f
6,6.0,56074,2.02303E+13,265650,2,6,19.43977,-99.15605,2,1,...,Entire condo,Entire home/apt,1 bath,"[""Luggage dropoff allowed"", ""Long term stays a...",650.0,t,29/03/23,02/04/11,21/01/23,f
7,7.0,61792,2.02303E+13,299558,2,3,19.41083,-99.18057,2,1,...,Private room in home,Private room,1 shared bath,"[""Heating - split type ductless system"", ""Whir...",1089.0,t,30/03/23,01/11/17,31/12/22,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17510,17508.0,6.51284E+17,2.02303E+13,403848214,5.3,6.2,19.4286725,-99.1616682,2,1,...,Entire rental unit,Entire home/apt,1.5 baths,"[""Ethernet connection"", ""MABE stainless steel ...",1713.0,t,30/03/23,03/07/22,23/03/23,t
17512,17510.0,6.55749E+17,2.02303E+13,10764020,5.3,6.2,19.41952,-99.17669,4,1,...,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Wine glasses"", ""Cleaning prod...",1402.0,t,29/03/23,31/07/22,18/03/23,t
17513,17511.0,6.53905E+17,2.02303E+13,460400195,1,1,19.45228,-99.13943,2,1,...,Private room in rental unit,Private room,1 private bath,"[""Free street parking"", ""Hot water kettle"", ""L...",400.0,t,29/03/23,26/06/22,12/03/23,t
17514,17512.0,6.53997E+17,2.02303E+13,257853661,15,15,19.36185,-99.2,4,1,...,Entire loft,Entire home/apt,1 bath,"[""Smoke alarm"", ""Luggage dropoff allowed"", ""Lo...",1124.0,t,29/03/23,03/07/22,09/03/23,t
17515,17513.0,6.55753E+17,2.02303E+13,23021265,13,14,19.40904853,-99.16711839,1,1,...,Private room in rental unit,Private room,1 shared bath,"[""Stainless steel oven"", ""Free street parking""...",570.0,t,29/03/23,31/07/22,27/01/23,f

In [ ]:
#Corroborar el filtro
filtroj['host_response_time'].unique()

array(['within an hour'], dtype=object)

In [ ]:
filtroj.to_csv("filtroj_MEX.csv")
from google.colab import files 
files.download("filtroj_MEX.csv")